name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'main'
      - 'feature/**'

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'

  test-spelling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check for spelling errors
        uses: streetsidesoftware/cspell-action@v7
        with:
          incremental_files_only: false
          verbose: true
